SEND_STRING_ENABLE = yes
OLED_DRIVER_ENABLE = yes
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LOCAL_GLCDFONT = yes
POINTING_DEVICE_ENABLE = yes
# JOYSTICK_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
